# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
image: registry.git.coop/webarch/containers/images/ansible:0.16.0
variables:
  PY_COLORS: "1"
  ANSIBLE_FORCE_COLOR: "1"
before_script:
  - chmod 700 $(pwd)
stages:
  - lint
lint:
  stage: lint
  script:
    - molecule lint
# vim: syntax=yaml
...
