---
- name: Systemd checks
  block:

    - name: List systemd unit files
      ansible.builtin.command: systemctl list-unit-files
      check_mode: false
      changed_when: false
      register: systemd_list_unit_files

    - name: Set a fact for the systemd unit files
      ansible.builtin.set_fact:
        systemd_unit_files_existing: "{{ systemd_list_unit_files.stdout | from_json | community.general.jc(systemctl-luf) }}"

    - name: Set a fact for the enabled systemd unit files
      ansible.builtin.set_fact:
        systemd_unit_files_enabled: "{{ systemd_unit_files_existing | community.general.json_query([?state == 'enabled'].unit_file) }}"

    - name: Debug enabled systemd unit files
      ansible.builtin.debug:
        var: systemd_unit_files_enabled
        verbosity: 2

  tags:
    - systemd
