# Copyright 2022-2025 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Systemd checks
  block:

    - name: Ensure that Ansible is version 2.13 or greater
      ansible.builtin.assert:
        that:
          - ansible_version.full is version('2.13.0', '>=')
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Find broken symlinks
      ansible.builtin.command: find /etc/systemd -xtype l
      check_mode: false
      changed_when: false
      register: systemd_list_broken_symlinks

    - name: Set a fact for the list of broken symlinks
      ansible.builtin.set_fact:
        systemd_broken_symlinks: "{{ systemd_list_broken_symlinks.stdout_lines }}"
      when: systemd_list_broken_symlinks.stdout_lines[0] is defined

    - name: Debug systemd_broken_symlinks
      ansible.builtin.debug:
        var: systemd_broken_symlinks
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      when:
        - systemd_broken_symlinks is defined
        - systemd_broken_symlinks != []
      tags:
        - debug

    - name: Find masked services, ones with /dev/null symlinks
      ansible.builtin.command: find /etc/systemd -lname /dev/null
      check_mode: false
      changed_when: false
      register: systemd_list_devnull_symlinks

    - name: Set a fact for the list of masked services, /dev/null symlinks
      ansible.builtin.set_fact:
        systemd_devnull_symlinks: "{{ systemd_list_devnull_symlinks.stdout_lines }}"
      when: systemd_list_devnull_symlinks.stdout_lines[0] is defined

    - name: List masked services, /dev/null symlinks
      ansible.builtin.debug:
        var: systemd_devnull_symlinks
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      when:
        - systemd_devnull_symlinks is defined
        - systemd_devnull_symlinks != []
      tags:
        - debug

    # TODO Find files that are not symlinks https://git.coop/webarch/systemd/-/issues/2
    #
    #      Replace systemctl list-unit-files with community.general.systemd_info module
    #      https://docs.ansible.com/ansible/latest/collections/community/general/systemd_info_module.html

    - name: List systemd unit files  # noqa command-instead-of-module
      ansible.builtin.command: systemctl list-unit-files
      check_mode: false
      changed_when: false
      register: systemd_list_unit_files

    - name: Debug list systemd unit files standard out
      ansible.builtin.debug:
        var: systemd_list_unit_files.stdout
        verbosity: 3
      tags:
        - debug

    - name: Set a fact for the systemd unit files
      ansible.builtin.set_fact:
        systemd_unit_files_existing: "{{ systemd_list_unit_files.stdout | string | community.general.jc('systemctl_luf') }}"

    - name: Debug existing systemd unit files
      ansible.builtin.debug:
        var: systemd_unit_files_existing
        verbosity: 2
      tags:
        - debug

    - name: Set a fact for the enabled systemd unit files
      ansible.builtin.set_fact:
        systemd_unit_files_enabled: "{{ systemd_unit_files_existing | community.general.json_query(systemd_unit_files_enabled_query) | sort }}"

    - name: Debug enabled systemd unit files
      ansible.builtin.debug:
        var: systemd_unit_files_enabled
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      tags:
        - debug

    # TODO Add checks for systemd_units variables

  tags:
    - systemd
