---
- name: Systemd checks
  block:

    - name: List systemd unit files
      ansible.builtin.command: jc systemctl list-unit-files
      check_mode: false
      changed_when: false
      register: systemd_list_unit_files

    - name: Debug list systemd unit files standard out
      ansible.builtin.debug:
        var: systemd_list_unit_files.stdout
        verbosity: 2

    - name: Set a fact for the systemd unit files
      ansible.builtin.set_fact:
        systemd_unit_files_existing: "{{ systemd_list_unit_files.stdout | community.general.jc('systemctl-luf') }}"

    - name: Set a fact for the enabled systemd unit files
      ansible.builtin.set_fact:
        systemd_unit_files_enabled: "{{ systemd_unit_files_existing | community.general.json_query(systemd_unit_files_enabled_jmespath_query) }}"
      vars:
        systemd_unit_files_enabled_jmespath_query: "[?state == 'enabled'].unit_file"

    - name: Debug enabled systemd unit files
      ansible.builtin.debug:
        var: systemd_unit_files_enabled
        verbosity: 2

  tags:
    - systemd
