# Copyright 2022-2025 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Systemd unit file edited
  block:

    - name: Conditionally set a variable with the list of sections
      block:

        - name: Set a fact for the existing systemd unit file sections
          ansible.builtin.set_fact:
            systemd_file_sections: "{{ systemd_file_vars.keys() }}"

        - name: Debug the existing systemd unit file sections
          ansible.builtin.debug:
            var: systemd_file_sections
            verbosity: 2
          tags:
            - debug

      when: systemd_conf_depth == 2

    - name: Backup copy of the existing systemd unit file present
      ansible.builtin.copy:
        src: "{{ systemd_file.path }}"
        dest: "{{ systemd_file_backup }}"
        mode: "0644"
        owner: root
        group: root
        remote_src: true
      vars:
        systemd_file_backup: "{{ systemd_file.path | ansible.builtin.dirname }}/.{{ systemd_file.path | ansible.builtin.basename }}.{{ ansible_facts.date_time.iso8601_basic_short }}.bak"
      when: systemd_file.conf != systemd_file_vars

    - name: Comment block present
      block:

        - name: Ansible managed comment absent from the top of the file
          ansible.builtin.lineinfile:
            path: "{{ systemd_file.path }}"
            line: "# {{ ansible_managed }}"
            state: absent
            mode: "0644"
            owner: root
            group: root

        - name: Comment present at the top of the systemd unit file
          ansible.builtin.blockinfile:
            path: "{{ systemd_file.path }}"
            block: "{{ systemd_file.comment | ansible.builtin.comment }}"
            insertbefore: BOF
            mode: "0644"
            owner: root
            group: root

      when:
        - systemd_file.comment is defined
        - systemd_file.comment | length > 0

    - name: Ansible managed comment present at the top of the file
      ansible.builtin.lineinfile:
        path: "{{ systemd_file.path }}"
        line: "# {{ ansible_managed }}"
        state: present
        insertbefore: BOF
        mode: "0644"
        owner: root
        group: root

    - name: Include the systemd unit file edited tasks without sections
      ansible.builtin.include_tasks: file_depth_one_edited.yml
      vars:
        systemd_section: "{{ systemd_file.conf }}"
      when: systemd_conf_depth == 1

    - name: Include the systemd unit file edited tasks for sections
      ansible.builtin.include_tasks: file_depth_two_edited.yml
      loop: "{{ systemd_file.conf | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: systemd_section
      when: systemd_conf_depth == 2

  tags:
    - systemd
...
