# Copyright 2022-2025 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Systemd unit file absent
  block:

    - name: Debug the systemd unit file variables
      ansible.builtin.debug:
        var: systemd_file
        verbosity: 2

    - name: Stat the systemd unit file
      ansible.builtin.stat:
        path: "{{ systemd_file.path }}"
      register: systemd_file_state

    - name: Systemd unit stopped
      ansible.builtin.systemd_service:
        service: "{{ systemd_unit.name }}"
        state: stopped
      when: systemd_file_state.stat.exists | bool

    - name: Systemd unit file absent, backup present
      ansible.builtin.command: "mv {{ systemd_file.path }} {{ systemd_file_backup }}"
      vars:
        systemd_file_backup: "{{ systemd_file.path | ansible.builtin.dirname }}/.{{ systemd_file.path | ansible.builtin.basename }}.{{ ansible_facts.date_time.iso8601_basic_short }}.bak"
      changed_when: true
      register: systemd_file_absent
      when: systemd_file_state.stat.exists | bool

    - name: Systemd daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
      when:
        - systemd_file_absent is defined
        - systemd_file_absent.changed is defined
        - systemd_file_absent.changed | bool

    - name: Stat the systemd unit file
      ansible.builtin.stat:
        path: "{{ systemd_file.path }}"
      register: systemd_file_state

  tags:
    - systemd
...
