---
- name: Remove broken symlinks
  block:

    - name: Set systemd_file_changed to false
      ansible.builtin.set_fact:
        systemd_file_changed: false

    - name: Delete broken symlinks
      block:

        - name: Delete broken symlinks
          ansible.builtin.file:
            path: "{{ systemd_broken_symlink }}"
            state: absent
          loop: "{{ systemd_broken_symlinks }}"
          loop_control:
            loop_var: systemd_broken_symlink
          register: systemd_broken_symlinks_absent
          notify: Systemd daemon-reload

        - name: Debug systemd_broken_symlinks_absent
          ansible.builtin.debug:
            var: systemd_broken_symlinks_absent
            verbosity: 2
          tags:
            - debug

      when:
        - systemd_delete_broken_symlinks | bool
        - systemd_broken_symlinks is defined

  tags:
    - systemd
...
