---
- name: Configure some systemd services
  block:

    - name: Include timesyncd tasks
      ansible.builtin.include_tasks: timesyncd.yml
      when: systemd_timesyncd

  when: systemd
  tags:
    - systemd
...
