---
- name: Configure some systemd services
  block:

    - name: Package systemd present
      ansible.builtin.apt:
        pkg:
          - systemd
        state: present

    - name: Checks
      ansible.builtin.include_tasks: checks.yml

    - name: Include timesyncd tasks
      ansible.builtin.include_tasks: timesyncd.yml
      when: systemd_timesyncd

  when: systemd
  tags:
    - systemd
...
