# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install package
  block:

    - name: Install from backports on Debian Buster and Bullseye
      block:

        - name: Run apt-cache policy
          ansible.builtin.command: "apt-cache policy {{ systemd_pkg }}"
          check_mode: false
          changed_when: false
          register: systemd_apt_cache_policy_pkg

        - name: Debug apt-cache policy results
          ansible.builtin.debug:
            var: systemd_apt_cache_policy_pkg.stdout_lines
            verbosity: 2
          when: systemd_apt_cache_policy_pkg.stdout_lines is defined

        - name: Install from backports
          ansible.builtin.apt:
            pkg: "{{ systemd_pkg }}"
            state: latest
            default_release: "{{ ansible_distribution_release }}-backports"
          when: ( "-backports" in systemd_apt_cache_policy_pkg.stdout )

      when: ansible_distribution_release is ansible.builtin.regex('^buster|bullseye$')

    - name: Package present
      ansible.builtin.apt:
        pkg: "{{ systemd_pkg }}"
        state: present

  tags:
    - systemd
...
