---
- name: Systemd timesyncd tasks
  block:

    - name: timesyncd configuration in place
      template:
        src: timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        mode: 0644
        owner: root
        group: root

    - name: Get the timedatectl status
      command: jc timedatectl status
      check_mode: false
      changed_when: false
      register: systemd_timedatectl_status

    - name: Debug the timedatectl status
      debug:
        var: systemd_timedatectl_status.stdout
        verbosity: 2

    - name: Enable systemd NTP
      command: timedatectl set-ntp true
      when:
        - systemd_timedatectl_status.stdout.ntp_service is defined
        - systemd_timedatectl_status.stdout.ntp_service != "active"

  tags:
    - systemd
...
