---
- name: Systemd unit absent
  block:

    - name: Debug the systemd unit variables
      ansible.builtin.debug:
        var: systemd_unit
        verbosity: 2

    - name: Systend unit stopped
      ansible.builtin.systemd:
        name: "{{ systemd_unit.name }}"
        state: stopped
      when: systemd_unit_file_name in systemd_unit_files_enabled
      vars:
        systemd_unit_file_name: "{{ systemd_unit.name }}.service"

    - name: Systemd packages absent
      ansible.builtin.apt:
        pkg: "{{ systemd_unit.pkgs }}"
        state: absent
      when:
        - systemd_unit.pkgs is defined
        - systemd_unit.pkgs | length > 0

    - name: Systemd unit files absent
      ansible.builtin.include_tasks: file_absent.yml
      loop: "{{ systemd_unit.files }}"
      loop_control:
        loop_var: systemd_file
        label: "{{ systemd_file.path | basename }}"

  tags:
    - systemd
...
