# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Systemd unit absent
  block:

    - name: Debug the systemd unit variables
      ansible.builtin.debug:
        var: systemd_unit
        verbosity: 2

    - name: Systend unit stopped
      ansible.builtin.systemd:
        name: "{{ systemd_unit.name }}"
        state: stopped
      register: systemd_unit_stopped
      when: systemd_unit_file_name in systemd_unit_files_enabled
      vars:
        systemd_unit_file_name: "{{ systemd_unit.name }}.service"

    - name: Systemd packages absent
      ansible.builtin.apt:
        pkg: "{{ systemd_unit.pkgs }}"
        state: absent
      register: systemd_unit_absent
      when:
        - systemd_unit.pkgs is defined
        - systemd_unit.pkgs | length > 0

    - name: Include check tasks
      ansible.builtin.include_tasks: checks.yml
      when: >-
        ( systemd_unit_stopped.changed | bool ) or
        ( systemd_unit_absent.changed | bool )

    - name: Systemd unit files absent
      ansible.builtin.include_tasks: file_absent.yml
      loop: "{{ systemd_unit.files }}"
      loop_control:
        loop_var: systemd_file
        label: "{{ systemd_file.path | ansible.builtin.basename }}"

  tags:
    - systemd
...
