---
- name: Systemd unit file present
  block:

    - name: Systemd unit file directory present
      ansible.builtin.file:
        path: "{{ systemd_unit.path | ansible.builtin.dirname }}"
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Systemd unit file present
      ansible.builtin.template:
        src: unit.j2
        dest: "{{ systemd_unit.path }}"
        backup: true
        mode: 0644
        owner: root
        group: root
      register: systend_unit_present
      notify: Reload systemd

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      when: systend_unit_present.changed | bool

    - name: Stat the systemd unit file
      ansible.builtin.stat:
        path: "{{ systemd_unit.path }}"
      register: systemd_unit_state

    - name: Unit state set
      ansible.builtin.systemd:
        name: "{{ systemd_unit.name }}"
        state: "{{ systemd_unit.unit_state | default('started') }}"
      when: systemd_unit_state.stat.exists | bool

  tags:
    - systemd
...
