# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects systemd Ansible role.
#
# The Webarchitects systemd Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects systemd Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Systemd unit absent
  block:

    - name: Debug the systemd unit variables
      ansible.builtin.debug:
        var: systemd_unit
        verbosity: 2

    - name: Systemd unit stopped and disabled
      ansible.builtin.systemd:
        name: "{{ systemd_unit.name }}"
        enabled: false
        state: stopped
      register: systemd_unit_stopped

    - name: Systemd daemon-reload  # noqa: no-handler
      ansible.builtin.systemd:
        daemon_reload: true
      when: systemd_unit_stopped.changed

    - name: Systemd packages absent
      ansible.builtin.apt:
        pkg: "{{ systemd_unit.pkgs }}"
        state: absent
      register: systemd_unit_absent
      when:
        - systemd_unit.pkgs is defined
        - systemd_unit.pkgs | length > 0

    - name: Systemd unit files absent
      ansible.builtin.include_tasks: file_absent.yml
      loop: "{{ systemd_unit.files }}"
      loop_control:
        loop_var: systemd_file
        label: "{{ systemd_file.path | ansible.builtin.basename }}"
      when:
        - systemd_unit.files is defined
        - systemd_unit.files | length > 0

  tags:
    - systemd
...
